packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@sentry-internal/node-cpu-profiler': false
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
overrides:
  glob@<11.1.0: 11.1.0
  minimatch@>=9.0.0 <9.0.7: 9.0.7
  protobufjs@>=8.0.0 <8.0.2: 8.0.2
  '@xmldom/xmldom@<0.8.13': 0.8.13
  fast-uri@<3.1.2: 3.1.2
