export const TEACHER_SUGGESTIONS = [
  'Wie kann ich eine Unterrichtsstunde über [Thema] planen?',
  'Welche kreativen Methoden gibt es, um [Thema] SchülerInnen zu vermitteln?',
  'Bitte gib mir ein Beispiel für ein Quiz zu [Thema] für die 7. Klasse.',
  'Wie erkläre ich komplexe Konzepte wie [Thema] auf einfache Weise?',
  'Was sind effektive Strategien, um SchülerInnen mit unterschiedlichen Lernniveaus zu fördern?',
  'Gib mir Vorschläge für Gruppenarbeiten zu [Thema].',
  'Wie kann ich digitale Tools im Unterricht einsetzen, um [Thema] zu unterrichten?',
  'Erstelle einen Wochenplan für die Vermittlung von [Thema].',
  'Welche aktuellen Forschungen gibt es zum Thema [Bildungsbereich]?',
  'Kannst du mir ein Unterrichtsmaterial zum Thema [Thema] vorschlagen?',
  'Welche Spiele oder Aktivitäten könnte ich nutzen, um [Thema] spielerisch zu unterrichten?',
  'Wie motiviere ich SchülerInnen, die wenig Interesse an [Fach] zeigen?',
  'Erstelle eine Checkliste für die Vorbereitung auf eine Klassenarbeit in [Fach].',
  'Welche Beispiele aus der Praxis gibt es, um [Thema] zu verdeutlichen?',
  'Wie kann ich SchülerInnen kritisches Denken beibringen?',
  'Hilf mir, eine Diskussion zu [Thema] vorzubereiten.',
  'Welche Übungen fördern die Teamarbeit in meiner Klasse?',
  'Gib mir ein Beispiel für ein Projekt, das ich mit SchülerInnen in [Fach] umsetzen kann.',
  'Wie kann ich Inklusion in meinem Unterricht fördern?',
];

export const STUDENT_SUGGESTIONS = [
  'Kannst du mir [Thema] in einfachen Worten erklären?',
  'Ich brauche Hilfe bei meinen Hausaufgaben zu [Thema].',
  'Welche Tipps gibt es, um mich besser auf einen Test in [Fach] vorzubereiten?',
  'Kannst du mir ein Beispiel für ein Referat über [Thema] geben?',
  'Wie löst man diese Aufgabe: [Aufgabe eingeben]?',
  'Erstelle eine Mindmap zu [Thema].',
  'Gib mir eine Zusammenfassung von [Thema] für die 8. Klasse.',
  'Welche Online-Ressourcen kann ich nutzen, um [Thema] zu lernen?',
  'Erkläre mir den Unterschied zwischen [Konzept 1] und [Konzept 2].',
  'Welche Beispiele aus dem Alltag gibt es für [Thema]?',
  'Kannst du eine Eselsbrücke für [Thema] erstellen?',
  'Wie kann ich mich besser organisieren, um in der Schule erfolgreich zu sein?',
  'Was bedeutet [Begriff]? Erkläre es mir bitte mit einem Beispiel.',
  'Gib mir ein Beispiel für eine kreative Präsentation zu [Thema].',
  'Welche Übungen kann ich machen, um [Fach] besser zu verstehen?',
  'Erstelle ein kurzes Quiz zu [Thema], das ich zur Übung nutzen kann.',
  'Wie funktioniert [Prozess/Technik]? Erkläre es Schritt für Schritt.',
  'Was sind typische Fehler bei [Thema], und wie kann ich sie vermeiden?',
  'Welche Bücher oder Filme behandeln das Thema [Thema]?',
  'Wie kann ich eine bessere Lernroutine entwickeln?',
];
